services:
  network-discovery:
    image: ghcr.io/presidio-federal/network-discovery-mcp:latest
    container_name: network-discovery-mcp
    environment:
      - ARTIFACT_DIR=/artifacts
      - BATFISH_HOST=localhost:9997
    volumes:
      - ./artifacts:/artifacts
    ports:
      - "8000:8000"
    depends_on:
      - batfish
    network_mode: "host"

  batfish:
    image: batfish/allinone:latest
    container_name: batfish
    ports:
      - "9997:9997"
    volumes:
      - ./artifacts:/data
    network_mode: "host"