services:
  network-discovery:
    image: ghcr.io/presidio-federal/network-discovery-mcp:latest
    container_name: network-discovery-mcp
    environment:
      - ARTIFACT_DIR=/artifacts
      - BATFISH_HOST=batfish
      - ENABLE_MCP=true
      - TRANSPORT=http
      - PORT=8000
      - BASE_PATH=${BASE_PATH:-}
    volumes:
      - ./artifacts:/artifacts
    ports:
      - "8000:8000"  # MCP port
    depends_on:
      - batfish
    networks:
      - discovery-network
    healthcheck:
      test: ["CMD-SHELL", "if [ -n \"$BASE_PATH\" ]; then curl -f http://localhost:8000$BASE_PATH/mcp || exit 1; else curl -f http://localhost:8000/mcp || exit 1; fi"]
      interval: 30s
      timeout: 10s
      retries: 3

  batfish:
    image: batfish/allinone:latest
    container_name: batfish
    ports:
      - "9997:9997"  # Batfish service port
      - "9996:9996"  # Coordinator service port
    volumes:
      - ./artifacts:/data
    networks:
      - discovery-network
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:9996/coordinator/v2/status || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  discovery-network:
    driver: bridge
